# Project: Diccionario-2do Parcial
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Traductor.o
LINKOBJ  = Traductor.o
LIBS     = -L"C:/Users/USUARIO/Downloads/Programas/Dev-Cpp/MinGW64/lib" -L"C:/Users/USUARIO/Downloads/Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/USUARIO/Downloads/Programas/Dev-Cpp/MinGW64/include" -I"C:/Users/USUARIO/Downloads/Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/USUARIO/Downloads/Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/USUARIO/Downloads/Programas/Dev-Cpp/MinGW64/include" -I"C:/Users/USUARIO/Downloads/Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/USUARIO/Downloads/Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/USUARIO/Downloads/Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Dicionario.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Traductor.o: Traductor.cpp
	$(CPP) -c Traductor.cpp -o Traductor.o $(CXXFLAGS)
